package practice.leetcode.easy;

/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        int[] checker = new int[26];
        for (char c : s.toCharArray()) checker[c - 'a']++;
        for (char c : t.toCharArray()) {
            if (--checker[c - 'a'] < 0) return c;
        }
        return ' ';
    }
}
